FROM clojure:lein
RUN gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
RUN curl -o /usr/local/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/1.4/gosu-$(dpkg --print-architecture)" \
    && curl -o /usr/local/bin/gosu.asc -SL "https://github.com/tianon/gosu/releases/download/1.4/gosu-$(dpkg --print-architecture).asc" \
    && gpg --verify /usr/local/bin/gosu.asc \
    && rm /usr/local/bin/gosu.asc \
    && chmod +x /usr/local/bin/gosu
WORKDIR /home/dev/src
EXPOSE 3000
ADD docker_dev_entrypoint.sh /usr/local/bin
RUN chmod +x /usr/local/bin/docker_dev_entrypoint.sh
ENTRYPOINT ["docker_dev_entrypoint.sh"]
